#端口号与网页前缀
server:
  port: 8080
spring:
  ## jsp支持
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
    static-path-pattern: /static/**
  ##关闭默认模板引擎
  thymeleaf:
    cache: false
    enable-spring-el-compiler: false

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB