#端口号与网页前缀
server:
  port: 8080
spring:
  ## jsp支持
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
    static-path-pattern: /static/**
  ##关闭默认模板引擎
  thymeleaf:
    cache: false
    enable-spring-el-compiler: false

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  #数据库连接配置信息
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#mybatis数据库映射文件配置
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


