#端口号与网页前缀
server:
  port: 8080
  servlet:
    context-path: /web
spring:
  ## jsp支持
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
  ##关闭默认模板引擎
  thymeleaf:
    cache: false
    enable-spring-el-compiler: false