#端口号与网页前缀
server:
  port: 8080
spring:
  ## jsp支持
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
    static-path-pattern: /static/**
  ##关闭默认模板引擎
  thymeleaf:
    cache: false
    enable-spring-el-compiler: false

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  #数据库连接配置信息
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#mybatis数据库映射文件配置
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/kift?serverTimezone=UTC
    #url: jdbc:mysql://192.168.1.15:3306/kift?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:dao/*Mapper.xml
  type-aliases-package: com.trs.zhq.entity

