package com.trs.zhq.util;

public class SelectFiledUtil {
	//"sj_chengxu"表对应的查询字段
	public static final String SJ_CHENGXU_FIELD = "SFILENAME;NFILELEN;SPROGTYPE;SPROJECTNAME;SIS_COMPRESS_SAVE;SUPLOADER;DUPLOADERTIME;SUSERCOMMENT";

	//"sj_erjinzhi"表对应的查询字段
	public static final String SJ_ERJINZHI_FIELD = "SFILENAME;NFILELEN;SPROGTYPE;SPROCESSORTYPE;SFPGATYPE;SEQUIPMENT;SPROJECTNAME;SUPLOADER;DUPLOADERTIME;SUSERCOMMENT";

	//"sj_fenxi"表对应的查询字段
	public static final String SJ_FENXI_FIELD = "SFILENAME;NFILELEN;SPROCESSORTYPE;SEQUIPMENT;SPROJECTNAME;SUPLOADER;DUPLOADERTIME;SUSERCOMMENT";

	//"sj_mocai"表对应的查询字段
	public static final String SJ_MOCAI_FIELD = "SFILENAME;NFILELEN;SCOMFREQSPAN;SSATELLITE_NAME;SORBIT_POS;SPOLARIZATION_TYPE;STRANSPONDR;SSTATION_NAME;SSQUIPMENT_NAME;SSQUIPMENT_CHAN;NCARRIER_FREQ;NIF_FREQ;NCARRIER_BAND;NDATA_SAMPLERATE;SFILTER_BAND;SSAMPLEDATA_TYPE;SSAMPLEGAIN_TYPE;SSAMPLEGAIN;NDATA_CARRIERFREQ;DDATA_RECBTIME;DDATA_RECETIME;NDATA_RECDURATION;NSAMPLE_BITS;NSAMPLE_VALID_BITS;SIS_COMPRESS_SAVE;SUPLOADER;SUSERCOMMENT";

	//"sj_pinpu"表对应的查询字段
	public static final String SJ_PINPU_FIELD = "SFILENAME;NFILELEN;SCOMFREQSPAN;SSATELLITE_NAME;SORBIT_POS;SPOLARIZATION_TYPE;STRANSPONDR;SSTATION_NAME;SSQUIPMENT_NAME;SSQUIPMENT_CHAN;NFREQ_START;NFREQ_STOP;NBANDDATA_SPLRATE;NBANDDATA_FFTNUM;NSIGLEVEL;NBANDDATA_TYPE;NSPECTRUM_DIVISION;DDATA_RECBTIME;DDATA_RECETIME;NDATA_RECDURATION;SIS_COMPRESS_SAVE;SUPLOADER;SUSERCOMMENT;BISTOSHARE";

	//"sj_shucai"表对应的查询字段
	public static final String SJ_SHUCAI_FIELD = "SFILENAME;NFILELEN;SCOMFREQSPAN;SSATELLITE_NAME;SORBIT_POS;SPOLARIZATION_TYPE;STRANSPONDR;NCARRIERFREQ;SSQUIPMENT_NAME;SSQUIPMENT_CHAN;DDATA_RECBTIME;DDATA_RECETIME;NDATA_RECDURATION;SMODULATIONMODE;NMODULATIONRATE;SCODETYPE;SCODERATIO;SSCRAMBLERTYPE;SSCRAMBLERRATIO;SMODFRAMETYPE;SFRAMERATIO;NINFORATE;SBUSINESSTYPE;NDEMOD_ERR;NDECOD_ERR;SIS_COMPRESS_SAVE;SUPLOADER;SUSERCOMMENT";

	//"sj_wangluo"表对应的查询字段
	public static final String SJ_WANGLUO_FIELD = "SFILENAME;NFILELEN;SCOMFREQSPAN;SSATELLITE_NAME;SORBIT_POS;SPOLARIZATION_TYPE;STRANSPONDR;NCARRIERFREQ;DDATA_RECBTIME;DDATA_RECETIME;NDATA_RECDURATION;SMODULATIONMODE;NMODULATIONRATE;SCODETYPE;SCODERATIO;SSCRAMBLERTYPE;SSCRAMBLERRATIO;SMODFRAMETYPE;SFRAMERATIO;NINFORATE;SBUSINESSTYPE;SNETSIGNALTYPE;NDEMOD_ERR;NDECOD_ERR;SNETDATA_TYPE;SIS_COMPRESS_SAVE;SUSERCOMMENT";

	//"sj_xinyuan"表对应的查询字段
	public static final String SJ_XINYUAN_FIELD = "SFILENAME;NFILELEN;SCOMFREQSPAN;SSATELLITE_NAME;SORBIT_POS;SPOLARIZATION_TYPE;STRANSPONDR;NCARRIERFREQ;SSOURCETYPE;SSOURCECODETYPE;NSOURCERATE;DDATA_RECBTIME;DDATA_RECETIME;NDATA_RECDURATION;SIS_COMPRESS_SAVE;SUPLOADER;SUSERCOMMENT";

	//"sj_wendang"表对应的查询字段
	public static final String SJ_WENDANG_FIELD = "DX_ID;DX_BIAOTI;DX_ZHENGWEN;DX_MIAOSHU;DX_FABUSHIJIAN;DX_RUKUSHIJIAN;DX_MIJI;DX_SHUXING;DX_FUJIAN;DX_LUJING;DX_LAIYUAN";

}
